### PR TITLE
Clean update

### PR DESCRIPTION
**Pull request by paolomassa**
Fixed bugs in 'stx_vis_clean':

1. keyword 'image_dim_in' is now cast as integer to avoid problems in the iterative loop;
2. the PSF utilized in the Clean process is now created with 'stx_vis_clean_psf'. In the previous version, the PSF was always created using natural weighting even when the keyword 'uniform_weighting' was set. 'stx_vis_clean_psf' solves this issue.

### CODE REVIEW

**Comment by samaloney** [comment]
So is there a bug in `vis_psf`? I guess if possible it would be better to update/fix vis_psf the essentially replicate? I'm not sure of the context so maybe this isn't possible.

**Review by afbattaglia — APPROVED** [review]
We've tested it with Säm and it works nicely. I do not know the answer to Shane's question regarding `vis_psf`, @paolomassa any ideas?

**Comment by paolomassa** [comment]
I finally found the bug in 'vis_psf' and I corrected it. Hence, 'stx_vis_clean_psf' is not needed anymore and I remove it. Please, @afbattaglia double check this new commit.

The only remaining issue is that the 'vis_psf' function in '/Users/admin/ssw/gen/idl/image/vis' should be replaced with what I uploaded to avoid repetition of the same function. Any idea about how to do this?

**Review by samaloney — APPROVED** [review]
Nice good to get the psf fix upstream in IDL/GEN

**Pull request merged**
