### PR TITLE
Rename aux files

### PR DESCRIPTION
**Pull request by FredSchuller**
Updated name of L2 AUX files to solo_ANC_stix-asp-ephemeris*

### CODE REVIEW

**Review by samaloney — COMMENTED** [review]
Looks good to me but should prob wait for @nicHoch too

**Comment by FredSchuller** [comment]
Sure, makes sense. I'll be off until Sept. 2nd but please proceed :-)

**Comment by FredSchuller** [comment]
Note that function _stx_get_ephemeris_file_ will now look for files with name '*stix-asp-ephemeris*.fits' and that will only work once the files have been updated on the data server.

**Comment by FredSchuller** [comment]
@samaloney @ennosigaeus 
I just created a new PR (#228) that includes all changes, also making things compatible with the previous AUX filenames.
Since I was about to generate a big mess when trying to include the recent changes, I preferred to start again from the up-to-date i4Ds/master branch and make only the necessary changes. Therefore PR #221 should simply be trashed...

**Pull request closed without merging**
