### PR TITLE
Updates for finer incident energy bins in SRM

### PR DESCRIPTION
**Pull request by mithunnps**
On exploring finer bin SRMs, it is noticed that having finer incident energy bins makes a difference to the predicted count spectrum in STIX for the same model, especially at low energies. Including new transmission files with finer binning to generate SRM files with finer incident energy bins of 10 eV in the 2-20 keV energy range and 100 eV in the 20-160 keV energy range and updates in the code to read from the new files.  The transmission files are generated from stixpy by modifying the energy values in stixpy.calibration.transmission.generate_transmission_tables(). When this is merged, maybe this small change in stixpy may also be merged for consistency. 

There are small differences in temperature (slight increase) and emission measure obtained with the new finer bin SRM compared to the previous versions.

### CODE REVIEW

**Comment by samaloney** [comment]
I think need to check if this is consistent with the default DRM energy binning as I think they need to match? Not clea how it would work if the transmission and DRM are not evaluated on the same energy grid?

**Review by samaloney — APPROVED** [review]
I think need to check if this is consistent with the default DRM energy binning as I think they need to match? Not clear how it would work if the transmission and DRM are not evaluated on the same energy grid?

**Comment by FredSchuller** [comment]
Hi @samaloney 
it's not 100% clear to me what needs to be checked and how to proceed... we have another colleague from India visiting us now, therefore it would be good if this issue could be solved relatively soon ;-)

**Comment by mithunnps** [comment]
> I think need to check if this is consistent with the default DRM energy binning as I think they need to match? Not clear how it would work if the transmission and DRM are not evaluated on the same energy grid?

Transmission files are reevaluated with the the finer energy bins using the stixpy routines mentioned above. New transmission files are also included in the commit. Perhaps the changes in stixpy to generate the transmission files also need to be committed, please see.

**Comment by samaloney** [comment]
Ok so I just had a look at the current version of the software and the drm bin edges go from 3.927 to 149.927 in steps of 0.146 (all in keV) but from the the name `stix_transmission_highres_20240711_010-100eVBin.csv` of the new file would suggest it goes from 10-100 with and but the contents seem to go from ~2 - 159 with a step of ~0.148. 

I don't think either of these match the DRM but maybe I'm missing something? 

If the goal is to evaluate the transmission on the same grid as the DRM then the contents of this function should be called with the bin centres obtained from the DRM.

I can modify the function to optionally take in an energy array which should make it easier in the future?

**Comment by mithunnps** [comment]
In the file name, "_010-100_" corresponds to the two bin sizes used. 10 eV for 2-20 keV and 100 eV for 20-160 keV. The name can be changed to be more appropriate as needed. The new transmission files in this commit are generated by modifying the energy bins defined in  stixpy/calibration/transmission.py to

energies = np.append(np.arange(2,20,0.01),np.arange(20,160,0.1)) * u.keV

However, this change has not been committed to GitHub. 

We have done fitting with finer DRM in XSPEC (by me) and OSPEX (by Alexander) and did not find a noticeable difference in performance. As mentioned in the first comment, there are some slight changes in the physical parameters.

**Comment by samaloney** [comment]
- [ ] @samaloney double check python code include lines

**Pull request merged**
